# Generated by Django 5.0 on 2023-12-16 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payAd',
            new_name='payAt',
        ),
    ]
