# Generated by Django 5.0 on 2023-12-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_payad_order_payat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/flower.jpg', null=True, upload_to=''),
        ),
    ]
