# Generated by Django 5.0 on 2023-12-19 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
