from django.urls import path
from .views import (get_product,
					get_products,
					get_top_products,				
					create_product,
					update_product,
					delete_product,
					MyTokenObtainPairView,
					get_user_profile, 
					get_users, 
					register_user, 
					update_user_profile, 
					get_orders_list,
					add_order_items, 
					get_order_by_id,
					update_order_to_paid,
					get_orders, delete_user,
					get_user_by_id,
					update_user,
					create_review)


urlpatterns = [
    path('users/login/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/register/', register_user, name='register'),
    path('users/profile/', get_user_profile, name='users_profile'),
    path('users/profile/update/', update_user_profile, name='update_user_profile'),
    path('users/', get_users, name='users'),
	path('users/<int:pk>/', get_user_by_id, name='user_by_id'),
	path('update/<int:pk>/', update_user, name='user_update'),
	path('delete/<int:pk>/', delete_user, name='user_delete'),
    path('products/', get_products, name='products'),
	path('products/create/', create_product, name='product_create'),
	path('products/<int:pk>/reviews/', create_review, name='review'),
	path('products/top/', get_top_products, name='top_products'),	
    path('products/<int:pk>/', get_product, name='product'),	
	path('products/update/<int:pk>/', update_product, name='product_update'),
	path('products/delete/<int:pk>/', delete_product, name='product_delete'),
	path('add/orderslist', get_orders_list, name='orders_list'),
	path('add/', add_order_items, name='orders_add'),
	path('add/orders', get_orders, name='orders'),
	path('add/<int:pk>/', get_order_by_id, name='order_by_id'),
	path('add/<int:pk>/pay/', update_order_to_paid, name='paid'),
]
