const products = [
    {
        '_id': '1',
        'name': 'Flower bucket',
        'image': '/images/flower.jpg',
        'description': 'flower',
        'brand': 'craft',
        'category': 'Flowers',
        'price': 40.99,
        'countInStock': 0,
        'rating': 4.5,
        'numReviews': 10,
    },
    {
        '_id': '2',
        'name': 'Flower bucket',
        'image': '/images/flower.jpg',
        'description': 'flower',
        'brand': 'craft',
        'category': 'Flowers',
        'price': 40.99,
        'countInStock': 7,
        'rating': 0,
        'numReviews': 7,
    },
    {
        '_id': '3',
        'name': 'Flower bucket',
        'image': '/images/flower.jpg',
        'description': 'flower',
        'brand': 'craft',
        'category': 'Flowers',
        'price': 51.10,
        'countInStock': 7,
        'rating': 10,
        'numReviews': 10,
    },
    {
        '_id': '4',
        'name': 'Flower bucket',
        'image': '/images/flower.jpg',
        'description': 'flower',
        'brand': 'craft',
        'category': 'Flowers',
        'price': 40.99,
        'countInStock': 7,
        'rating': 7.3,
        'numReviews': 10,
    },
    {
        '_id': '5',
        'name': 'Flower bucket',
        'image': '/images/flower.jpg',
        'description': 'flower',
        'brand': 'craft',
        'category': 'Flowers',
        'price': 40.99,
        'countInStock': 7,
        'rating': 1,
        'numReviews': 10,
    },
    {
        '_id': '6',
        'name': 'Flower bucket',
        'image': '/images/flower.jpg',
        'description': 'flower',
        'brand': 'craft',
        'category': 'Flowers',
        'price': 40.99,
        'countInStock': 7,
        'rating': 0,
        'numReviews': 10,
    },
]
export default products